name: Dockerhub Description

on:
  push:
    branches:
    - master

jobs:
  update_docker_hub_metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Docker hub metadata
      uses: docker://mpepping/docker-hub-metadata-github-action
      env:
        IMAGE: synixebrett/arma3server
        DOCKER_USERNAME: synixebrett
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
